[package]
name = "codex-redis-vector"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
bincode = "1"
small-world-rs = "1.1.1"
fastrand = "2"
