[package]
name = "codex-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "net", "io-util", "time"] }
codex-redis-vector = { path = "../codex-redis-vector" }

[dev-dependencies]
tempfile = "3"
