[package]
name = "codex-ollama"
version = "0.1.0"
edition = "2024"

[dependencies]
codex-core = { path = "../codex-core" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
wiremock = "0.6"
